name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for wrong lock files
        run: |
          if [ -f "package-lock.json" ]; then
            echo "❌ Error: package-lock.json found. This project uses pnpm!"
            exit 1
          fi
          if [ -f "yarn.lock" ]; then
            echo "❌ Error: yarn.lock found. This project uses pnpm!"
            exit 1
          fi
          if [ ! -f "pnpm-lock.yaml" ]; then
            echo "❌ Error: pnpm-lock.yaml not found!"
            exit 1
          fi
          echo "✅ Correct lock file (pnpm-lock.yaml) found"

  lint-and-test:
    runs-on: ubuntu-latest
    needs: check-lockfile
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run ESLint
        run: pnpm lint
        
      - name: TypeScript Check
        run: pnpm tsc --noEmit
        
      - name: Run Tests with Coverage
        run: pnpm test:cov
        
      - name: Build
        run: pnpm build
        
      - name: Upload Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/